import type { ObjectAsset } from '@/types/design';

// Pascal-derived, locally served floor/free-placement catalog. Wall and ceiling
// attached fixtures remain excluded until Corbel supports host-surface placement.
export const OBJECT_CATALOG: ObjectAsset[] = [
  {
    id: "cactus",
    name: "Cactus",
    category: "furniture",
    tags: ["cactus","rack","stand","hanger","sculpture","decor","modern","contemporary","pop","green","organizer","storage","sculptural"],
    modelUrl: "/items/cactus/model.glb",
    thumbnailUrl: "/items/cactus/thumbnail.webp",
    dimensions: [0.34,0.39,0.27],
    offset: [-0.0039,0,0],
    modelRotation: [0,0,0],
    modelScale: [1,1,1],
    color: "#9a6b3f",
  },
  {
    id: "tv-stand",
    name: "TV Stand",
    category: "furniture",
    tags: ["floor","storage"],
    modelUrl: "/items/tv-stand/model.glb",
    thumbnailUrl: "/items/tv-stand/thumbnail.webp",
    dimensions: [1.86,0.35,0.32],
    offset: [0,0.2066,0],
    modelRotation: [0,0,0],
    modelScale: [1,1,1],
    color: "#9a6b3f",
  },
  {
    id: "single-bed",
    name: "Single Bed",
    category: "furniture",
    tags: ["floor","bedroom"],
    modelUrl: "/items/single-bed/model.glb",
    thumbnailUrl: "/items/single-bed/thumbnail.webp",
    dimensions: [1.08,0.6,2.14],
    offset: [-0.0024,0,-0.013],
    modelRotation: [0,0,0],
    modelScale: [1,1,1],
    color: "#9a6b3f",
  },
  {
    id: "livingroom-chair",
    name: "Livingroom Chair",
    category: "furniture",
    tags: ["chair","armchair","seating","lounge","upholstered","modern","fabric","furniture","minimalist","comfort","accent","lounger"],
    modelUrl: "/items/livingroom-chair/model.glb",
    thumbnailUrl: "/items/livingroom-chair/thumbnail.webp",
    dimensions: [1.1,0.75,1.07],
    offset: [0,0.0001,0.0053],
    modelRotation: [0,0,0],
    modelScale: [1,1,1],
    color: "#9a6b3f",
  },
  {
    id: "small-indoor-plant",
    name: "Small Plant",
    category: "furniture",
    tags: ["countertop","decor","vegetation"],
    modelUrl: "/items/small-indoor-plant/model.glb",
    thumbnailUrl: "/items/small-indoor-plant/thumbnail.webp",
    dimensions: [0.4,0.67,0.38],
    offset: [-0.0106,0,0.0067],
    modelRotation: [0,0,0],
    modelScale: [1,1,1],
    color: "#9a6b3f",
  },
  {
    id: "column",
    name: "Column",
    category: "furniture",
    tags: ["column","pillar","pedestal","plinth","stand","marble","stone","classical","roman","greek","decorative","architectural","antique","support","base"],
    modelUrl: "/items/column/model.glb",
    thumbnailUrl: "/items/column/thumbnail.webp",
    dimensions: [0.5,2.5,0.5],
    offset: [0,1.25,0],
    modelRotation: [0,0,0],
    modelScale: [1,1,1],
    color: "#9a6b3f",
  },
  {
    id: "barbell",
    name: "Barbell",
    category: "furniture",
    tags: ["barbell","weight","steel","iron","metal","gym","fitness","industrial","workout","strength","training","lifting","chrome","exercise"],
    modelUrl: "/items/barbell/model.glb",
    thumbnailUrl: "/items/barbell/thumbnail.webp",
    dimensions: [0.38,0.38,1.72],
    offset: [0,0,0],
    modelRotation: [0,0,0],
    modelScale: [1,1,1],
    color: "#9a6b3f",
  },
  {
    id: "toy",
    name: "Toy",
    category: "furniture",
    tags: ["floor","kids","decor"],
    modelUrl: "/items/toy/model.glb",
    thumbnailUrl: "/items/toy/thumbnail.webp",
    dimensions: [0.29,0.49,0.34],
    offset: [0,0,0],
    modelRotation: [0,0,0],
    modelScale: [1,1,1],
    color: "#9a6b3f",
  },
  {
    id: "barbell-stand",
    name: "Barbell Stand",
    category: "furniture",
    tags: ["rack","stand","holder","storage","metal","steel","industrial","fitness","gym","weightlifting","training","minimalist","black","organizer"],
    modelUrl: "/items/barbell-stand/model.glb",
    thumbnailUrl: "/items/barbell-stand/thumbnail.webp",
    dimensions: [1.34,1.22,1.72],
    offset: [-0.0173,0,0],
    modelRotation: [0,0,0],
    modelScale: [1,1,1],
    color: "#9a6b3f",
  },
  {
    id: "books",
    name: "Books",
    category: "furniture",
    tags: ["books","novels","literature","reading","vintage","classic","decorative","paper","leather","library","study","office","decor","shelf","antique"],
    modelUrl: "/items/books/model.glb",
    thumbnailUrl: "/items/books/thumbnail.webp",
    dimensions: [0.22,0.22,0.18],
    offset: [-0.0851,0.003,0.0209],
    modelRotation: [0,0,0],
    modelScale: [1,1,1],
    color: "#9a6b3f",
  },
  {
    id: "stool",
    name: "Stool",
    category: "furniture",
    tags: ["floor","seating"],
    modelUrl: "/items/stool/model.glb",
    thumbnailUrl: "/items/stool/thumbnail.webp",
    dimensions: [0.52,1.16,0.55],
    offset: [0,0,0],
    modelRotation: [0,0,0],
    modelScale: [1,1,1],
    color: "#9a6b3f",
  },
  {
    id: "pool-table",
    name: "Pool table",
    category: "furniture",
    tags: ["pool","billiards","snooker","table","recreation","leisure","entertainment","wood","felt","gaming","traditional","luxury","classic","hobby","furniture"],
    modelUrl: "/items/pool-table/model.glb",
    thumbnailUrl: "/items/pool-table/thumbnail.webp",
    dimensions: [2.11,0.98,3.5],
    offset: [0,0,0],
    modelRotation: [0,0,0],
    modelScale: [1,1,1],
    color: "#9a6b3f",
  },
  {
    id: "bookshelf",
    name: "Bookshelf",
    category: "furniture",
    tags: ["bookshelf","bookcase","shelving","storage","organizer","modern","minimalist","wood","metal","industrial","library","office","furniture","display","timber"],
    modelUrl: "/items/bookshelf/model.glb",
    thumbnailUrl: "/items/bookshelf/thumbnail.webp",
    dimensions: [0.93,1.99,0.33],
    offset: [0,0,0.0032],
    modelRotation: [0,0,0],
    modelScale: [1,1,1],
    color: "#9a6b3f",
  },
  {
    id: "coat-rack",
    name: "Coat Rack",
    category: "furniture",
    tags: ["coatrack","rack","hanger","valet","organizer","storage","entryway","hallway","minimalist","metal","wood","mudroom","hooks","clothes"],
    modelUrl: "/items/coat-rack/model.glb",
    thumbnailUrl: "/items/coat-rack/thumbnail.webp",
    dimensions: [0.33,1.76,0.33],
    offset: [0,0,0],
    modelRotation: [0,0,0],
    modelScale: [1,1,1],
    color: "#9a6b3f",
  },
  {
    id: "car-toy",
    name: "Car Toy",
    category: "furniture",
    tags: ["car","toy","vehicle","racer","play","nursery","playroom","wooden","vintage","decor","kids","child","classic","miniature","hobby"],
    modelUrl: "/items/car-toy/model.glb",
    thumbnailUrl: "/items/car-toy/thumbnail.webp",
    dimensions: [0.31,0.38,0.6],
    offset: [0.0005,0.0005,-0.0075],
    modelRotation: [0,0,0],
    modelScale: [1,1,1],
    color: "#9a6b3f",
  },
  {
    id: "bedside-table",
    name: "Bedside Table",
    category: "furniture",
    tags: ["nightstand","table","bedroom","storage","wood","modern","minimalist","stand","drawer","furniture","cabinet","bedside"],
    modelUrl: "/items/bedside-table/model.glb",
    thumbnailUrl: "/items/bedside-table/thumbnail.webp",
    dimensions: [0.45,0.48,0.46],
    offset: [0.0005,0,-0.0062],
    modelRotation: [0,0,0],
    modelScale: [1,1,1],
    color: "#9a6b3f",
  },
  {
    id: "sofa",
    name: "Sofa",
    category: "furniture",
    tags: ["floor","seating"],
    modelUrl: "/items/sofa/model.glb",
    thumbnailUrl: "/items/sofa/thumbnail.webp",
    dimensions: [2.06,0.74,1.01],
    offset: [-0.0023,0.009,0.0459],
    modelRotation: [0,0,0],
    modelScale: [1,1,1],
    color: "#9a6b3f",
  },
  {
    id: "bunkbed",
    name: "Bunkbed",
    category: "furniture",
    tags: ["bunkbed","bed","sleeper","loft","bedroom","kids","wood","metal","modern","sleeping","ladder","rustic","dormitory","furniture"],
    modelUrl: "/items/bunkbed/model.glb",
    thumbnailUrl: "/items/bunkbed/thumbnail.webp",
    dimensions: [1.65,1.55,0.99],
    offset: [0,0,-0.0886],
    modelRotation: [0,0,0],
    modelScale: [1,1,1],
    color: "#9a6b3f",
  },
  {
    id: "office-table",
    name: "Office Table",
    category: "furniture",
    tags: ["desk","table","workstation","furniture","office","work","study","writing","modern","minimalist","industrial","wood","metal"],
    modelUrl: "/items/office-table/model.glb",
    thumbnailUrl: "/items/office-table/thumbnail.webp",
    dimensions: [1.51,0.76,0.62],
    offset: [-0.0001,0,-0.0052],
    modelRotation: [0,0,0],
    modelScale: [1,1,1],
    color: "#9a6b3f",
  },
  {
    id: "dining-table",
    name: "Dining Table",
    category: "furniture",
    tags: ["table","dining","furniture","wood","modern","minimalist","kitchen","eating","surface","contemporary","gathering","walnut"],
    modelUrl: "/items/dining-table/model.glb",
    thumbnailUrl: "/items/dining-table/thumbnail.webp",
    dimensions: [2.16,0.7,0.95],
    offset: [0,0,-0.0077],
    modelRotation: [0,0,0],
    modelScale: [1,1,1],
    color: "#9a6b3f",
  },
  {
    id: "guitar",
    name: "Guitar",
    category: "furniture",
    tags: ["guitar","instrument","musical","wood","acoustic","vintage","classic","decor","mahogany","string","art","hobby"],
    modelUrl: "/items/guitar/model.glb",
    thumbnailUrl: "/items/guitar/thumbnail.webp",
    dimensions: [0.4,1.18,0.09],
    offset: [-0.0009,0.3197,-0.0129],
    modelRotation: [0,0,0],
    modelScale: [1,1,1],
    color: "#9a6b3f",
  },
  {
    id: "trash-bin",
    name: "Trash Bin",
    category: "furniture",
    tags: ["floor"],
    modelUrl: "/items/trash-bin/model.glb",
    thumbnailUrl: "/items/trash-bin/thumbnail.webp",
    dimensions: [0.35,0.59,0.42],
    offset: [0,0,0],
    modelRotation: [0,0,0],
    modelScale: [1,1,1],
    color: "#9a6b3f",
  },
  {
    id: "table-lamp",
    name: "Table Lamp",
    category: "furniture",
    tags: ["countertop","lighting"],
    modelUrl: "/items/table-lamp/model.glb",
    thumbnailUrl: "/items/table-lamp/thumbnail.webp",
    dimensions: [0.29,0.74,0.67],
    offset: [0,0,0],
    modelRotation: [0,0,0],
    modelScale: [1,1,1],
    color: "#9a6b3f",
  },
  {
    id: "closet",
    name: "Closet",
    category: "furniture",
    tags: ["closet","wardrobe","armoire","cabinet","storage","organization","wood","bedroom","modern","minimalist","clothing","apparel","cupboard","locker"],
    modelUrl: "/items/closet/model.glb",
    thumbnailUrl: "/items/closet/thumbnail.webp",
    dimensions: [1.95,2.26,0.6],
    offset: [0,0,-0.0141],
    modelRotation: [0,0,0],
    modelScale: [1,1,1],
    color: "#9a6b3f",
  },
  {
    id: "coffee-table",
    name: "Coffee Table",
    category: "furniture",
    tags: ["table","cocktail","wood","modern","minimalist","furniture","living","lounge","walnut","metal","glass","surface","decor"],
    modelUrl: "/items/coffee-table/model.glb",
    thumbnailUrl: "/items/coffee-table/thumbnail.webp",
    dimensions: [1.72,0.3,1.04],
    offset: [0,0,0.0089],
    modelRotation: [0,0,0],
    modelScale: [1,1,1],
    color: "#9a6b3f",
  },
  {
    id: "dining-chair",
    name: "Dining Chair",
    category: "furniture",
    tags: ["chair","seating","dining","furniture","modern","wood","upholstered","kitchen","seat","minimalist","timber","bistro"],
    modelUrl: "/items/dining-chair/model.glb",
    thumbnailUrl: "/items/dining-chair/thumbnail.webp",
    dimensions: [0.47,0.87,0.5],
    offset: [0,0,0.0016],
    modelRotation: [0,0,0],
    modelScale: [1,1,1],
    color: "#9a6b3f",
  },
  {
    id: "dresser",
    name: "Dresser",
    category: "furniture",
    tags: ["dresser","chest","bureau","storage","bedroom","drawers","wood","modern","organization","cabinet","rustic","minimalist"],
    modelUrl: "/items/dresser/model.glb",
    thumbnailUrl: "/items/dresser/thumbnail.webp",
    dimensions: [1.23,0.73,0.61],
    offset: [0,0,-0.0066],
    modelRotation: [0,0,0],
    modelScale: [1,1,1],
    color: "#9a6b3f",
  },
  {
    id: "indoor-plant",
    name: "Indoor Plant",
    category: "furniture",
    tags: ["plant","greenery","botanical","foliage","houseplant","organic","natural","modern","minimalist","tropical","decor","accent","green","ceramic"],
    modelUrl: "/items/indoor-plant/model.glb",
    thumbnailUrl: "/items/indoor-plant/thumbnail.webp",
    dimensions: [0.69,1.63,0.83],
    offset: [-0.0506,0,0.0664],
    modelRotation: [0,0,0],
    modelScale: [1,1,1],
    color: "#9a6b3f",
  },
  {
    id: "ironing-board",
    name: "Ironing Board",
    category: "furniture",
    tags: ["ironing","board","laundry","foldable","metal","utility","pressing","collapsible","stand","table","organization","industrial"],
    modelUrl: "/items/ironing-board/model.glb",
    thumbnailUrl: "/items/ironing-board/thumbnail.webp",
    dimensions: [1.31,0.96,0.48],
    offset: [0,0,0],
    modelRotation: [0,0,0],
    modelScale: [1,1,1],
    color: "#9a6b3f",
  },
  {
    id: "double-bed",
    name: "Double Bed",
    category: "furniture",
    tags: ["bed","bedstead","double","frame","bedroom","sleeping","modern","minimalist","upholstered","wood","sleep","furniture","contemporary"],
    modelUrl: "/items/double-bed/model.glb",
    thumbnailUrl: "/items/double-bed/thumbnail.webp",
    dimensions: [1.52,0.71,2],
    offset: [0.0042,0,-0.0277],
    modelRotation: [0,0,0],
    modelScale: [1,1,1],
    color: "#9a6b3f",
  },
  {
    id: "floor-lamp",
    name: "Floor Lamp",
    category: "furniture",
    tags: ["lamp","luminaire","light","torchere","lighting","illumination","metal","brass","modern","minimalist","industrial","decor","ambient","reading","sleek"],
    modelUrl: "/items/floor-lamp/model.glb",
    thumbnailUrl: "/items/floor-lamp/thumbnail.webp",
    dimensions: [0.7,1.86,0.69],
    offset: [0.0341,0.0045,0.0219],
    modelRotation: [0,0,0],
    modelScale: [1,1,1],
    color: "#9a6b3f",
  },
  {
    id: "easel",
    name: "Easel",
    category: "furniture",
    tags: ["easel","stand","tripod","art","studio","wood","display","canvas","atelier","presentation","wooden","sketching","painting","decor"],
    modelUrl: "/items/easel/model.glb",
    thumbnailUrl: "/items/easel/thumbnail.webp",
    dimensions: [0.99,2.32,0.55],
    offset: [0,0.0402,0.0116],
    modelRotation: [0,0,0],
    modelScale: [1,1,1],
    color: "#9a6b3f",
  },
  {
    id: "lounge-chair",
    name: "Lounge Chair",
    category: "furniture",
    tags: ["chair","armchair","seating","lounge","seat","modern","contemporary","minimalist","comfort","relaxation","upholstered","interior","furniture"],
    modelUrl: "/items/lounge-chair/model.glb",
    thumbnailUrl: "/items/lounge-chair/thumbnail.webp",
    dimensions: [0.68,1.03,1.26],
    offset: [0,0.0034,0.0894],
    modelRotation: [0,0,0],
    modelScale: [1,1,1],
    color: "#9a6b3f",
  },
  {
    id: "office-chair",
    name: "Office Chair",
    category: "furniture",
    tags: ["chair","seating","ergonomic","swivel","office","desk","mesh","leather","modern","task","workspace","professional","computer"],
    modelUrl: "/items/office-chair/model.glb",
    thumbnailUrl: "/items/office-chair/thumbnail.webp",
    dimensions: [0.66,1.16,0.69],
    offset: [0.0024,0.0015,0.0332],
    modelRotation: [0,0,0],
    modelScale: [1,1,1],
    color: "#9a6b3f",
  },
  {
    id: "piano",
    name: "Piano",
    category: "furniture",
    tags: ["piano","instrument","musical","grand","upright","keyboard","wood","polished","lacquer","ebony","classic","traditional","music","entertainment","luxury"],
    modelUrl: "/items/piano/model.glb",
    thumbnailUrl: "/items/piano/thumbnail.webp",
    dimensions: [1.54,1.44,0.69],
    offset: [0,0,0.0162],
    modelRotation: [0,0,0],
    modelScale: [1,1,1],
    color: "#9a6b3f",
  },
  {
    id: "rectangular-carpet",
    name: "Rectangular Carpet",
    category: "furniture",
    tags: ["carpet","rug","mat","textile","woven","rectangular","modern","wool","cotton","minimalist","decor","plush"],
    modelUrl: "/items/rectangular-carpet/model.glb",
    thumbnailUrl: "/items/rectangular-carpet/thumbnail.webp",
    dimensions: [2.78,0.04,1.81],
    offset: [0,0,0],
    modelRotation: [0,0,0],
    modelScale: [1,1,1],
    color: "#9a6b3f",
  },
  {
    id: "round-carpet",
    name: "Round Carpet",
    category: "furniture",
    tags: ["carpet","rug","mat","circular","modern","minimalist","scandinavian","textile","woven","decor","accent","wool","fiber","interior"],
    modelUrl: "/items/round-carpet/model.glb",
    thumbnailUrl: "/items/round-carpet/thumbnail.webp",
    dimensions: [1.99,0.05,1.99],
    offset: [0,0,0],
    modelRotation: [0,0,0],
    modelScale: [1,1,1],
    color: "#9a6b3f",
  },
  {
    id: "threadmill",
    name: "Threadmill",
    category: "furniture",
    tags: ["floor","fitness"],
    modelUrl: "/items/threadmill/model.glb",
    thumbnailUrl: "/items/threadmill/thumbnail.webp",
    dimensions: [2.1,1.45,0.9],
    offset: [0,0,0],
    modelRotation: [0,0,0],
    modelScale: [1,1,1],
    color: "#9a6b3f",
  },
  {
    id: "sewing-machine",
    name: "Sewing Machine",
    category: "appliance",
    tags: ["sewing","machine","appliance","tailor","craft","hobby","textile","metal","plastic","vintage","modern","industrial","mending","stitching"],
    modelUrl: "/items/sewing-machine/model.glb",
    thumbnailUrl: "/items/sewing-machine/thumbnail.webp",
    dimensions: [0.83,0.68,0.32],
    offset: [0,0,0],
    modelRotation: [0,0,0],
    modelScale: [1,1,1],
    color: "#64748b",
  },
  {
    id: "television",
    name: "Television",
    category: "appliance",
    tags: ["floor","electronics"],
    modelUrl: "/items/television/model.glb",
    thumbnailUrl: "/items/television/thumbnail.webp",
    dimensions: [1.62,1.07,0.38],
    offset: [0,0,0],
    modelRotation: [0,0,0],
    modelScale: [1,1,1],
    color: "#64748b",
  },
  {
    id: "ac-block",
    name: "AC block",
    category: "appliance",
    tags: ["conditioner","cooler","hvac","cooling","appliance","vent","modern","minimalist","metal","industrial","white","utility","ventilation","unit","climate"],
    modelUrl: "/items/ac-block/model.glb",
    thumbnailUrl: "/items/ac-block/thumbnail.webp",
    dimensions: [1.06,0.95,1.06],
    offset: [0,0,0],
    modelRotation: [0,0,0],
    modelScale: [0.79,0.79,0.79],
    color: "#64748b",
  },
  {
    id: "stereo-speaker",
    name: "Stereo Speaker",
    category: "appliance",
    tags: ["floor","electronics"],
    modelUrl: "/items/stereo-speaker/model.glb",
    thumbnailUrl: "/items/stereo-speaker/thumbnail.webp",
    dimensions: [0.23,1,0.34],
    offset: [0,0,-0.0129],
    modelRotation: [0,0,0],
    modelScale: [1,1,1],
    color: "#64748b",
  },
  {
    id: "toaster",
    name: "Toaster",
    category: "appliance",
    tags: ["countertop","electronics"],
    modelUrl: "/items/toaster/model.glb",
    thumbnailUrl: "/items/toaster/thumbnail.webp",
    dimensions: [0.28,0.23,0.17],
    offset: [-0.0057,0,0],
    modelRotation: [0,0,0],
    modelScale: [1,1,1],
    color: "#64748b",
  },
  {
    id: "kettle",
    name: "Kettle",
    category: "appliance",
    tags: ["kettle","teapot","boiler","electric","kitchen","appliance","metal","steel","modern","tea","coffee","boiling","beverage","breakfast"],
    modelUrl: "/items/kettle/model.glb",
    thumbnailUrl: "/items/kettle/thumbnail.webp",
    dimensions: [0.24,0.25,0.18],
    offset: [-0.026,0,0],
    modelRotation: [0,0,0],
    modelScale: [1,1,1],
    color: "#64748b",
  },
  {
    id: "hydrant",
    name: "Hydrant",
    category: "appliance",
    tags: ["hydrant","faucet","spigot","valve","metal","iron","industrial","vintage","retro","plumbing","water","utility","outdoor","garden","red"],
    modelUrl: "/items/hydrant/model.glb",
    thumbnailUrl: "/items/hydrant/thumbnail.webp",
    dimensions: [0.64,0.88,0.64],
    offset: [-0.0046,0,-0.0008],
    modelRotation: [0,0,0],
    modelScale: [1,1,1],
    color: "#64748b",
  },
  {
    id: "coffee-machine",
    name: "Coffee Machine",
    category: "appliance",
    tags: ["coffee","machine","maker","espresso","brewer","kitchen","appliance","modern","metal","sleek","black","silver","beverage","brewing"],
    modelUrl: "/items/coffee-machine/model.glb",
    thumbnailUrl: "/items/coffee-machine/thumbnail.webp",
    dimensions: [0.16,0.24,0.23],
    offset: [0.0003,0.0003,-0.0366],
    modelRotation: [0,0,0],
    modelScale: [1,1,1],
    color: "#64748b",
  },
  {
    id: "iron",
    name: "Iron",
    category: "appliance",
    tags: ["iron","steamer","laundry","clothing","modern","metal","plastic","ceramic","garment","pressing","household","utility","appliance","sleek"],
    modelUrl: "/items/iron/model.glb",
    thumbnailUrl: "/items/iron/thumbnail.webp",
    dimensions: [0.36,0.24,0.21],
    offset: [0.026,0,0],
    modelRotation: [0,0,0],
    modelScale: [1,1,1],
    color: "#64748b",
  },
  {
    id: "computer",
    name: "Computer",
    category: "appliance",
    tags: ["computer","desktop","workstation","monitor","technology","office","electronics","modern","sleek","metal","silver","minimalist","hardware","productivity"],
    modelUrl: "/items/computer/model.glb",
    thumbnailUrl: "/items/computer/thumbnail.webp",
    dimensions: [0.68,0.48,0.19],
    offset: [0,0,0],
    modelRotation: [0,0,0],
    modelScale: [1,1,1],
    color: "#64748b",
  },
  {
    id: "bathroom-sink",
    name: "Bathroom Sink",
    category: "bathroom",
    tags: ["sink","basin","lavatory","washbasin","vanity","modern","minimalist","ceramic","porcelain","white","plumbing","washing","bathroom","hygiene"],
    modelUrl: "/items/bathroom-sink/model.glb",
    thumbnailUrl: "/items/bathroom-sink/thumbnail.webp",
    dimensions: [1.83,0.97,0.63],
    offset: [0.1037,0,0.0221],
    modelRotation: [0,0,0],
    modelScale: [1,1,1],
    color: "#0f766e",
  },
  {
    id: "shower-angle",
    name: "Angle Shower",
    category: "bathroom",
    tags: ["shower","enclosure","cubicle","modern","glass","corner","bathroom","chrome","minimalist","washing","hygiene","plumbing","stall","sleek"],
    modelUrl: "/items/shower-angle/model.glb",
    thumbnailUrl: "/items/shower-angle/thumbnail.webp",
    dimensions: [0.83,1.81,0.83],
    offset: [0.4102,0,-0.4102],
    modelRotation: [0,0,0],
    modelScale: [1,1,1],
    color: "#0f766e",
  },
  {
    id: "washing-machine",
    name: "Washing Machine",
    category: "bathroom",
    tags: ["floor","large","electronics"],
    modelUrl: "/items/washing-machine/model.glb",
    thumbnailUrl: "/items/washing-machine/thumbnail.webp",
    dimensions: [0.6,0.86,0.53],
    offset: [0,0,-0.0114],
    modelRotation: [0,0,0],
    modelScale: [1,1,1],
    color: "#0f766e",
  },
  {
    id: "shower-rug",
    name: "Shower Rug",
    category: "bathroom",
    tags: ["rug","mat","bathmat","absorbent","cotton","chenille","modern","soft","minimalist","spa","bathroom","hygiene","plush","microfiber","woven"],
    modelUrl: "/items/shower-rug/model.glb",
    thumbnailUrl: "/items/shower-rug/thumbnail.webp",
    dimensions: [0.77,0.03,0.48],
    offset: [0,0,0],
    modelRotation: [0,0,0],
    modelScale: [1,1,1],
    color: "#0f766e",
  },
  {
    id: "bathtub",
    name: "Bathtub",
    category: "bathroom",
    tags: ["bathtub","tub","bath","soaking","modern","minimalist","porcelain","acrylic","ceramic","bathroom","relaxation","spa"],
    modelUrl: "/items/bathtub/model.glb",
    thumbnailUrl: "/items/bathtub/thumbnail.webp",
    dimensions: [2.34,0.79,1.11],
    offset: [0,0,0],
    modelRotation: [0,0,0],
    modelScale: [1,1,1],
    color: "#0f766e",
  },
  {
    id: "laundry-bag",
    name: "Laundry Bag",
    category: "bathroom",
    tags: ["laundry","bag","hamper","basket","canvas","fabric","storage","organization","modern","minimalist","utility","cleaning","linen"],
    modelUrl: "/items/laundry-bag/model.glb",
    thumbnailUrl: "/items/laundry-bag/thumbnail.webp",
    dimensions: [0.46,0.78,0.48],
    offset: [0,0,-0.0006],
    modelRotation: [0,0,0],
    modelScale: [1,1,1],
    color: "#0f766e",
  },
  {
    id: "shower-square",
    name: "Squared Shower",
    category: "bathroom",
    tags: ["floor","large"],
    modelUrl: "/items/shower-square/model.glb",
    thumbnailUrl: "/items/shower-square/thumbnail.webp",
    dimensions: [0.81,1.8,0.81],
    offset: [0.4,0,-0.3995],
    modelRotation: [0,0,0],
    modelScale: [1,1,1],
    color: "#0f766e",
  },
  {
    id: "drying-rack",
    name: "Drying Rack",
    category: "bathroom",
    tags: ["dryer","rack","airer","laundry","hanging","organizer","metal","steel","modern","minimalist","storage","bathroom"],
    modelUrl: "/items/drying-rack/model.glb",
    thumbnailUrl: "/items/drying-rack/thumbnail.webp",
    dimensions: [1.79,1.05,0.58],
    offset: [0,-0.0058,0],
    modelRotation: [0,0,0],
    modelScale: [1,1,1],
    color: "#0f766e",
  },
  {
    id: "toilet",
    name: "Toilet",
    category: "bathroom",
    tags: ["floor","large"],
    modelUrl: "/items/toilet/model.glb",
    thumbnailUrl: "/items/toilet/thumbnail.webp",
    dimensions: [0.42,0.82,0.72],
    offset: [0,0,-0.2393],
    modelRotation: [0,0,0],
    modelScale: [1,1,1],
    color: "#0f766e",
  },
  {
    id: "microwave",
    name: "Microwave",
    category: "kitchen",
    tags: ["microwave","oven","appliance","kitchen","cooking","heating","metal","steel","modern","sleek","black","silver","electronics","glass","contemporary"],
    modelUrl: "/items/microwave/model.glb",
    thumbnailUrl: "/items/microwave/thumbnail.webp",
    dimensions: [0.52,0.27,0.41],
    offset: [0,0,-0.0225],
    modelRotation: [0,0,0],
    modelScale: [1,1,1],
    color: "#b45309",
  },
  {
    id: "cutting-board",
    name: "Cutting Board",
    category: "kitchen",
    tags: ["board","wood","kitchen","prep","chopping","serving","block","rustic","culinary","timber","natural","chef","cooking"],
    modelUrl: "/items/cutting-board/model.glb",
    thumbnailUrl: "/items/cutting-board/thumbnail.webp",
    dimensions: [0.27,0.07,0.41],
    offset: [0,0,0],
    modelRotation: [0,0,0],
    modelScale: [1,1,1],
    color: "#b45309",
  },
  {
    id: "kitchen-utensils",
    name: "Kitchen Utensils",
    category: "kitchen",
    tags: ["utensils","tools","kitchenware","cooking","prep","steel","silicone","wood","modern","gadgets","accessories","silverware","chef","serving","baking"],
    modelUrl: "/items/kitchen-utensils/model.glb",
    thumbnailUrl: "/items/kitchen-utensils/thumbnail.webp",
    dimensions: [0.23,0.49,0.21],
    offset: [0.0184,0,0.0165],
    modelRotation: [0,0,0],
    modelScale: [1,1,1],
    color: "#b45309",
  },
  {
    id: "kitchen-counter",
    name: "Kitchen Counter",
    category: "kitchen",
    tags: ["counter","countertop","island","surface","workspace","stone","granite","marble","modern","kitchen","cooking","prep","sleek","polished"],
    modelUrl: "/items/kitchen-counter/model.glb",
    thumbnailUrl: "/items/kitchen-counter/thumbnail.webp",
    dimensions: [1.96,0.73,0.63],
    offset: [0.0012,0,-0.0004],
    modelRotation: [0,0,0],
    modelScale: [1,1,1],
    color: "#b45309",
  },
  {
    id: "kitchen-cabinet",
    name: "Kitchen Cabinet",
    category: "kitchen",
    tags: ["cabinet","cupboard","storage","kitchen","shaker","pantry","wood","timber","modern","contemporary","minimalist","organization"],
    modelUrl: "/items/kitchen-cabinet/model.glb",
    thumbnailUrl: "/items/kitchen-cabinet/thumbnail.webp",
    dimensions: [1.65,1.09,0.77],
    offset: [0,0.0004,0],
    modelRotation: [0,0,0],
    modelScale: [1,1,1],
    color: "#b45309",
  },
  {
    id: "kitchen",
    name: "Kitchen",
    category: "kitchen",
    tags: ["kitchen","cabinetry","cabinet","island","cooking","storage","modern","contemporary","minimalist","wood","marble","culinary","pantry"],
    modelUrl: "/items/kitchen/model.glb",
    thumbnailUrl: "/items/kitchen/thumbnail.webp",
    dimensions: [2.38,1.03,0.84],
    offset: [0,0,0],
    modelRotation: [0,0,0],
    modelScale: [1,1,1],
    color: "#b45309",
  },
  {
    id: "frying-pan",
    name: "Frying Pan",
    category: "kitchen",
    tags: ["frying","pan","skillet","cookware","kitchen","cooking","metal","steel","nonstick","culinary","modern","chef","stove","utensil"],
    modelUrl: "/items/frying-pan/model.glb",
    thumbnailUrl: "/items/frying-pan/thumbnail.webp",
    dimensions: [0.36,0.09,0.64],
    offset: [0,0,0],
    modelRotation: [0,0,0],
    modelScale: [1,1,1],
    color: "#b45309",
  },
  {
    id: "fruits",
    name: "Fruits",
    category: "kitchen",
    tags: ["fruit","produce","food","kitchen","dining","centerpiece","tabletop","vibrant","fresh","organic","natural","accessory","decor","colorful"],
    modelUrl: "/items/fruits/model.glb",
    thumbnailUrl: "/items/fruits/thumbnail.webp",
    dimensions: [0.39,0.27,0.39],
    offset: [0,0,0],
    modelRotation: [0,0,0],
    modelScale: [1,1,1],
    color: "#b45309",
  },
  {
    id: "fridge",
    name: "Fridge",
    category: "kitchen",
    tags: ["fridge","refrigerator","freezer","appliance","kitchen","storage","cooling","metal","steel","modern","industrial","minimalist","silver","sleek"],
    modelUrl: "/items/fridge/model.glb",
    thumbnailUrl: "/items/fridge/thumbnail.webp",
    dimensions: [0.7,1.92,0.72],
    offset: [0,0,-0.0507],
    modelRotation: [0,0,0],
    modelScale: [1,1,1],
    color: "#b45309",
  },
  {
    id: "wine-bottle",
    name: "Wine Bottle",
    category: "kitchen",
    tags: ["countertop","decor"],
    modelUrl: "/items/wine-bottle/model.glb",
    thumbnailUrl: "/items/wine-bottle/thumbnail.webp",
    dimensions: [0.38,0.35,0.17],
    offset: [-0.0461,0,0.0135],
    modelRotation: [0,0,0],
    modelScale: [1,1,1],
    color: "#b45309",
  },
  {
    id: "stove",
    name: "Stove",
    category: "kitchen",
    tags: ["floor","large"],
    modelUrl: "/items/stove/model.glb",
    thumbnailUrl: "/items/stove/thumbnail.webp",
    dimensions: [0.92,0.85,0.76],
    offset: [0.0043,0,-0.0505],
    modelRotation: [0,0,0],
    modelScale: [1,1,1],
    color: "#b45309",
  },
  {
    id: "ball",
    name: "Ball",
    category: "outdoor",
    tags: ["ball","sphere","orb","globe","round","modern","minimalist","decor","garden","patio","sculpture","ornament","accent","circular","contemporary"],
    modelUrl: "/items/ball/model.glb",
    thumbnailUrl: "/items/ball/thumbnail.webp",
    dimensions: [0.24,0.24,0.24],
    offset: [-0.0001,0.1194,-0.0001],
    modelRotation: [0,0,0],
    modelScale: [1,1,1],
    color: "#4d7c0f",
  },
  {
    id: "bush",
    name: "Bush",
    category: "outdoor",
    tags: ["bush","shrub","plant","greenery","foliage","hedge","natural","organic","lush","landscaping","garden","yard","botanical","outdoor","decorative"],
    modelUrl: "/items/bush/model.glb",
    thumbnailUrl: "/items/bush/thumbnail.webp",
    dimensions: [3,1.04,1.01],
    offset: [-0.1463,0.0094,-0.113],
    modelRotation: [0,0,0],
    modelScale: [0.96,0.96,0.96],
    color: "#4d7c0f",
  },
  {
    id: "basket-hoop",
    name: "Basket Hoop",
    category: "outdoor",
    tags: ["hoop","basketball","rim","net","goal","sporty","recreation","outdoor","metal","steel","athletic","game","play","leisure","activity"],
    modelUrl: "/items/basket-hoop/model.glb",
    thumbnailUrl: "/items/basket-hoop/thumbnail.webp",
    dimensions: [0.58,1.78,0.56],
    offset: [0,0,0],
    modelRotation: [0,0,0],
    modelScale: [1,1,1],
    color: "#4d7c0f",
  },
  {
    id: "parking-spot",
    name: "Parking Spot",
    category: "outdoor",
    tags: ["parking","space","stall","driveway","pavement","asphalt","concrete","urban","industrial","utility","vehicle","outdoor"],
    modelUrl: "/items/parking-spot/model.glb",
    thumbnailUrl: "/items/parking-spot/thumbnail.webp",
    dimensions: [4.95,0.12,2.28],
    offset: [0,0.0121,0.015],
    modelRotation: [0,0,0],
    modelScale: [0.9,1,0.78],
    color: "#4d7c0f",
  },
  {
    id: "palm",
    name: "Palm",
    category: "outdoor",
    tags: ["palm","tree","plant","tropical","exotic","foliage","greenery","botanical","garden","patio","outdoor","lush","organic","nature"],
    modelUrl: "/items/palm/model.glb",
    thumbnailUrl: "/items/palm/thumbnail.webp",
    dimensions: [0.525,4.5,0.496],
    offset: [0,0.08,0],
    modelRotation: [0,0,0],
    modelScale: [0.37,0.37,0.37],
    color: "#4d7c0f",
  },
  {
    id: "sunbed",
    name: "Sunbed",
    category: "outdoor",
    tags: ["leisure","seating","floor"],
    modelUrl: "/items/sunbed/model.glb",
    thumbnailUrl: "/items/sunbed/thumbnail.webp",
    dimensions: [0.86,1.13,1.01],
    offset: [0,0.0516,0.0137],
    modelRotation: [0,0,0],
    modelScale: [1,1,1],
    color: "#4d7c0f",
  },
  {
    id: "fir-tree",
    name: "Fir",
    category: "outdoor",
    tags: ["fir","tree","plant","evergreen","conifer","foliage","greenery","natural","garden","outdoor","botanical","rustic","alpine","woodland"],
    modelUrl: "/items/fir-tree/model.glb",
    thumbnailUrl: "/items/fir-tree/thumbnail.webp",
    dimensions: [0.27,3,0.23],
    offset: [0.02,0.05,-0.06],
    modelRotation: [0,0,0],
    modelScale: [1,1,1],
    color: "#4d7c0f",
  },
  {
    id: "tree",
    name: "Tree",
    category: "outdoor",
    tags: ["vegetation"],
    modelUrl: "/items/tree/model.glb",
    thumbnailUrl: "/items/tree/thumbnail.webp",
    dimensions: [0.79,5,0.85],
    offset: [-0.02,0.17,-0.04],
    modelRotation: [0,0,0],
    modelScale: [0.65,0.65,0.65],
    color: "#4d7c0f",
  },
  {
    id: "skate",
    name: "Skate",
    category: "outdoor",
    tags: ["leisure","kids","floor"],
    modelUrl: "/items/skate/model.glb",
    thumbnailUrl: "/items/skate/thumbnail.webp",
    dimensions: [0.86,0.11,0.2],
    offset: [0,0,0],
    modelRotation: [0,0,0],
    modelScale: [1,1,1],
    color: "#4d7c0f",
  },
  {
    id: "outdoor-playhouse",
    name: "Outdoor Playhouse",
    category: "outdoor",
    tags: ["playhouse","cottage","cabin","fort","wood","cedar","garden","backyard","kids","children","play","recreation","outdoor","rustic","timber"],
    modelUrl: "/items/outdoor-playhouse/model.glb",
    thumbnailUrl: "/items/outdoor-playhouse/thumbnail.webp",
    dimensions: [0.3,0.47,0.72],
    offset: [-0.0062,0,-0.0268],
    modelRotation: [0,0,0],
    modelScale: [1,1,1],
    color: "#4d7c0f",
  },
  {
    id: "patio-umbrella",
    name: "Patio Umbrella",
    category: "outdoor",
    tags: ["umbrella","parasol","shade","canopy","sunshade","outdoor","patio","garden","modern","polyester","fabric","aluminum","poolside","protection","summer"],
    modelUrl: "/items/patio-umbrella/model.glb",
    thumbnailUrl: "/items/patio-umbrella/thumbnail.webp",
    dimensions: [0.139,3.603,0.15],
    offset: [0,0,0],
    modelRotation: [0,0,0],
    modelScale: [1,1,1],
    color: "#4d7c0f",
  },
  {
    id: "pillar",
    name: "Pillar",
    category: "outdoor",
    tags: ["pillar","column","pedestal","plinth","stone","concrete","classical","architectural","garden","ornament","decoration","support"],
    modelUrl: "/items/pillar/model.glb",
    thumbnailUrl: "/items/pillar/thumbnail.webp",
    dimensions: [0.34,1.26,0.3],
    offset: [0,0,0],
    modelRotation: [0,0,0],
    modelScale: [1,1,1],
    color: "#4d7c0f",
  },
  {
    id: "scooter",
    name: "Scooter",
    category: "outdoor",
    tags: ["scooter","kickscooter","transport","mobility","outdoor","wheels","metal","aluminum","modern","sleek","urban","active","travel","ride","commute"],
    modelUrl: "/items/scooter/model.glb",
    thumbnailUrl: "/items/scooter/thumbnail.webp",
    dimensions: [0.85,0.85,0.45],
    offset: [0.1127,0.0017,0.1744],
    modelRotation: [0,0,0],
    modelScale: [1,1,1],
    color: "#4d7c0f",
  },
  {
    id: "tesla",
    name: "Tesla Model Y",
    category: "outdoor",
    tags: ["tesla","car","vehicle","automobile","electric","modern","minimalist","sleek","metal","glass","luxury","transportation","commuting"],
    modelUrl: "/items/tesla/model.glb",
    thumbnailUrl: "/items/tesla/thumbnail.webp",
    dimensions: [1.98,1.62,4.76],
    offset: [0.0039,-0.0102,-0.0148],
    modelRotation: [0,0,0],
    modelScale: [1,1,1],
    color: "#4d7c0f",
  }
];

export const OBJECT_CATALOG_BY_ID = Object.fromEntries(
  OBJECT_CATALOG.map((asset) => [asset.id, asset])
) as Record<string, ObjectAsset>;

export const OBJECT_CATEGORIES = [
  { id: 'all', label: 'All' },
  { id: 'furniture', label: 'Furniture' },
  { id: 'appliance', label: 'Appliances' },
  { id: 'bathroom', label: 'Bathroom' },
  { id: 'kitchen', label: 'Kitchen' },
  { id: 'outdoor', label: 'Outdoor' },
] as const;
