import { NextResponse } from 'next/server';
import type { FloorPlan, ValidationResult } from '@/types/design';

export const runtime = 'nodejs';

function isFloorPlan(value: unknown): value is FloorPlan {
  if (!value || typeof value !== 'object') return false;
  const plan = value as Partial<FloorPlan>;
  return typeof plan.name === 'string'
    && typeof plan.width === 'number'
    && typeof plan.height === 'number'
    && typeof plan.scale === 'number'
    && Array.isArray(plan.walls)
    && Array.isArray(plan.rooms)
    && Array.isArray(plan.doors)
    && Array.isArray(plan.windows);
}

function asMarkdownCell(value: unknown): string {
  return String(value ?? '—').replace(/[|\n]/g, ' ');
}

function reportMarkdown(plan: FloorPlan, results: ValidationResult[]): string {
  const errors = results.filter((result) => result.type === 'error');
  const warnings = results.filter((result) => result.type === 'warning');
  const infos = results.filter((result) => result.type === 'info');
  const lines = [
    '# Corbel standards and compliance report',
    '',
    '> Educational design feedback only. This report is not professional approval, a code determination, or a substitute for review by a qualified local practitioner.',
    '',
    '## Plan summary',
    '',
    '| Field | Value |',
    '| --- | --- |',
    '| Plan | ' + asMarkdownCell(plan.name) + ' |',
    '| Overall size | ' + asMarkdownCell(plan.width) + ' × ' + asMarkdownCell(plan.height) + ' mm |',
    '| Drawing scale | ' + asMarkdownCell(plan.scale) + ' px/m |',
    '| Walls | ' + plan.walls.length + ' |',
    '| Rooms | ' + plan.rooms.length + ' |',
    '| Doors | ' + plan.doors.length + ' |',
    '| Windows | ' + plan.windows.length + ' |',
    '',
    '## Findings',
    '',
    '| Severity | Rule | Message | Suggested next step |',
    '| --- | --- | --- | --- |',
    ...(results.length > 0
      ? results.map((result) => '| ' + asMarkdownCell(result.type) + ' | ' + asMarkdownCell(result.rule) + ' | ' + asMarkdownCell(result.message) + ' | ' + asMarkdownCell(result.remediation) + ' |')
      : ['| info | — | No current validation findings were supplied. | Continue reviewing the design as it develops. |']),
    '',
    'Summary: ' + errors.length + ' error(s), ' + warnings.length + ' warning(s), ' + infos.length + ' informational note(s).',
    '',
    '## Room schedule',
    '',
    '| Room | Type | Area (m²) |',
    '| --- | --- | ---: |',
    ...plan.rooms.map((room) => '| ' + asMarkdownCell(room.name) + ' | ' + asMarkdownCell(room.type) + ' | ' + asMarkdownCell(room.area) + ' |'),
    '',
    '## Opening schedule',
    '',
    '| Type | ID | Wall | Width (mm) |',
    '| --- | --- | --- | ---: |',
    ...plan.doors.map((door) => '| Door | ' + asMarkdownCell(door.id) + ' | ' + asMarkdownCell(door.wallId) + ' | ' + asMarkdownCell(door.width) + ' |'),
    ...plan.windows.map((window) => '| Window | ' + asMarkdownCell(window.id) + ' | ' + asMarkdownCell(window.wallId) + ' | ' + asMarkdownCell(window.width) + ' |'),
    '',
    'Generated by Corbel.',
    '',
  ];
  return lines.join('\n');
}

function reportJson(plan: FloorPlan, results: ValidationResult[]): string {
  return JSON.stringify({
    generatedAt: new Date().toISOString(),
    disclaimer: 'Educational design feedback only. This is not professional approval or a code determination.',
    summary: {
      name: plan.name,
      width: plan.width,
      height: plan.height,
      scale: plan.scale,
      walls: plan.walls.length,
      rooms: plan.rooms.length,
      doors: plan.doors.length,
      windows: plan.windows.length,
      errors: results.filter((result) => result.type === 'error').length,
      warnings: results.filter((result) => result.type === 'warning').length,
      infos: results.filter((result) => result.type === 'info').length,
    },
    findings: results,
    plan,
  }, null, 2);
}

function csvCell(value: unknown): string {
  return '"' + String(value ?? '').replace(/"/g, '""').replace(/[\n\r]/g, ' ') + '"';
}

function reportCsv(plan: FloorPlan, results: ValidationResult[]): string {
  const rows = [
    ['section', 'type', 'id', 'name', 'rule', 'message', 'remediation', 'width_mm', 'height_mm', 'area_m2'],
    ...results.map((result) => ['finding', result.type, result.targetId, '', result.rule, result.message, result.remediation ?? '', '', '', '']),
    ...plan.rooms.map((room) => ['room', room.type ?? '', room.id, room.name, '', '', '', '', '', String(room.area)]),
    ...plan.doors.map((door) => ['door', '', door.id, '', '', '', '', String(door.width), '', '']),
    ...plan.windows.map((window) => ['window', '', window.id, '', '', '', '', String(window.width), String(window.height), '']),
    ...plan.walls.map((wall) => ['wall', wall.type, wall.id, '', '', '', '', '', '', '']),
  ];
  return rows.map((row) => row.map(csvCell).join(',')).join('\n') + '\n';
}

function htmlEscape(value: string): string {
  return value.replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;').replace(/"/g, '&quot;');
}

function reportHtml(plan: FloorPlan, results: ValidationResult[]): string {
  return '<!doctype html><html><head><meta charset="utf-8"><title>' + htmlEscape(plan.name) + ' compliance report</title><style>'
    + 'body{font:14px system-ui,-apple-system,sans-serif;color:#20252b;max-width:900px;margin:40px auto;padding:0 24px;line-height:1.5}'
    + 'h1{font-size:28px;margin-bottom:8px}p{color:#5d6670}.notice{padding:12px 16px;background:#f3f6f8;border:1px solid #d7dde2;border-radius:6px;margin:24px 0}table{border-collapse:collapse;width:100%;margin:16px 0}th,td{border:1px solid #d7dde2;padding:8px;text-align:left}button{padding:10px 16px;border:1px solid #aeb8c2;background:#fff;border-radius:6px;cursor:pointer}@media print{button{display:none}body{margin:0;max-width:none}}'
    + '</style></head><body><button onclick="window.print()">Print / Save as PDF</button><h1>Corbel standards and compliance report</h1><p>'
    + htmlEscape(plan.name) + '</p><div class="notice">Educational design feedback only. This report is not professional approval, a code determination, or a substitute for review by a qualified local practitioner.</div><h2>Report data</h2><pre>'
    + htmlEscape(reportMarkdown(plan, results)) + '</pre></body></html>';
}

export async function POST(request: Request) {
  try {
    const body = await request.json() as { floorPlan?: unknown; validationResults?: unknown; format?: unknown };
    if (!isFloorPlan(body.floorPlan)) {
      return NextResponse.json({ error: 'A valid floor plan is required.' }, { status: 400 });
    }
    const results = Array.isArray(body.validationResults) ? body.validationResults as ValidationResult[] : [];
    const format = body.format === 'json' || body.format === 'csv' || body.format === 'html' ? body.format : 'markdown';
    const content = format === 'json' ? reportJson(body.floorPlan, results) : format === 'csv' ? reportCsv(body.floorPlan, results) : format === 'html' ? reportHtml(body.floorPlan, results) : reportMarkdown(body.floorPlan, results);
    const contentType = format === 'json' ? 'application/json; charset=utf-8' : format === 'csv' ? 'text/csv; charset=utf-8' : format === 'html' ? 'text/html; charset=utf-8' : 'text/markdown; charset=utf-8';
    return new NextResponse(content, {
      headers: {
        'Content-Type': contentType,
        'Content-Disposition': 'attachment; filename="corbel-compliance-report.' + (format === 'markdown' ? 'md' : format) + '"',
        'Cache-Control': 'no-store',
      },
    });
  } catch {
    return NextResponse.json({ error: 'Unable to create the compliance report.' }, { status: 400 });
  }
}
